name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workspace:
        type: string
        description: The name of the workspace to deploy to
        required: true
        default: 'pbi-next-step'
      environment:
        type: choice
        description: The environment to deploy to
        required: true
        default: 'DEV'
        options:
        - DEV
        - PRD
  
env:
  environment_name: ${{ github.event.inputs.environment || 'PRD' }}
  workspace_name: ${{ github.event.inputs.workspace || vars.workspace || 'pbi-next-step' }}

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'PRD' }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install fabric-cicd
        run: |
          python -m pip install fabric-cicd

      - name: Run Deployment Script 
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
        run: >
          python scripts/deploy.py
          --spn-auth
          --workspace "$workspace_name"
          --environment "$environment_name"
          --src "./src"
